### ISSUE TITLE
docs_install.md

### ISSUE THREAD

**Issue by chenkehao** [binstd/tplan#19]
https://github.com/binstd/tplan/blob/master/project/ipfs/TODO-trans/docs_install.md

1.回复“翻译认领”

2.收到站长回复OK后 开始翻译

3.翻译完成后提交这个问题下面

**Comment by zhouzian1** [comment]
翻译认领

**Comment by chenkehao** [comment]
OK
已经标记 可以开始翻译

**Comment by chenkehao** [comment]
有个问题 看看这个和这篇是不是重复？ https://github.com/binstd/tplan/blob/master/project/ipfs/TODO-trans/installing-with-ipfs-update.md

**Comment by zhouzian1** [comment]
大多数都是相同的，正好也是我翻译的，里面存在一些不一样的地方。

**Comment by zhouzian1** [comment]
# 安装 IPFS

这里有跟多方法将IPFS安装在你的电脑上，我们通常会建议通过安装包的方式对IPFS进行安装，同时也提供了一些其他的选择：

* 通过安装包安装（推荐）
* 使用ipfs-update安装
* 通过编译源码安装
* 升级IPFS
* 快速定位问题

值得注意的是，这些指导手册都会用到命令行工具。我们用`$`来指示命令的提示-就是在需要输入命令的开头。不过输出的执行结构是没有这个符号的。

## 通过安装包安装
首先，下载适合你操作系统的IPFS版本：

[下载适合你操作系统的IPFS](https://dist.ipfs.io/#go-ipfs)

### Mac OS X 和 Linux
当你下载好安装包之后，解压并将`ipfs`的库文件拷到可执行的路径下，使用`install.sh`脚本进行安装：
```
$ tar xvfz go-ipfs.tar.gz
$ cd go-ipfs
$ ./install.sh

```
测试结果:

```
$ ipfs help
USAGE:

        ipfs - Global p2p merkle-dag filesystem.
    ...
```
恭喜你！现在你已经成功将IPFS安装在你的电脑上。

[开始使用IPFS](https://docs.ipfs.io/introduction/usage/)

### Windows
当你下载好安装包之后，解压并将`ipfs.exe`拷贝到可执行的路径上`%PATH%`。

测试结果:
```
$ ipfs help
USAGE:
        
     ipfs - Global p2p merkle-dag filesystem.
    ...
```
恭喜你！现在你已经成功将IPFS安装在你的电脑上。

[开始使用IPFS](https://docs.ipfs.io/introduction/usage/)

## 通过ipfs-update安装
ipfs-update 是一个命令行工具，用来安装与升级ipfs库文件。
### 下载ipfs-update
可以在[https://dist.ipfs.io/#ipfs-update](https://dist.ipfs.io/#ipfs-update)下载到适合你操作系统的`ipfs-update`

如果你拥有Go环境（>=1.8）,你也可以这样安装他

`$ go get -u github.com/ipfs/ipfs-update`

当你安装新版本的ipfs或者是升级，请确认使用最新版本`ipfs`。

### 通过ipfs-update来安装ipfs
`ipfs-update versions`会列举出所有可以使用的`ipfs`版本，并提供下载。

```
$ ipfs-update versions
v0.3.2
v0.3.4
v0.3.5
v0.3.6
v0.3.7
v0.3.8
v0.3.9
v0.3.10
v0.3.11
v0.4.0
v0.4.1
v0.4.2
v0.4.3
v0.4.4
v0.4.5
v0.4.6
v0.4.7-rc1
```

`ipfs-update install latest`将会安装最新的可用版本：

```
$ ipfs-update install latest
fetching go-ipfs version v0.4.7-rc1
binary downloaded, verifying...
success!
stashing old binary
installing new binary to /home/hector/go/bin/ipfs
checking if repo migration is needed...
Installation complete!
```

值得注意的是最新版本可能会存在稳定性问题（例如：发布候选列表里带有vX.X.X-rcX格式的）。所以建议指定版本进行安装，例如：`ipfs-update install v0.4.6`。

## 源码安装
>警告：之前你可以通过使用`go get`来安装IPFS,但是这种方式今后将不再支持。

如果你愿意的话，你也可以通过源码编译的方式构建IPFS。如果你用的是Mac OS X或者是Linux 可以参考readme[安装指南](https://github.com/ipfs/go-ipfs#build-from-source)。如果你是Windows，请参考这份[操作文档](https://github.com/ipfs/go-ipfs/blob/master/docs/windows.md)。

## 升级IPFS
`ipfs`升级（或者降级）会涉及到仓库的升级，通过使用[fs-repo-migrations](https://dist.ipfs.io/#fs-repo-migrations)工具。

### 使用ipfs-update升级
当你需要时安装最新或者历史版本的时候（正如文章之前提到过），使用`ipfs-update install`会下载并执行`fs-repo-migrations`。这是最新简单的升级方式。

>警告：请确认在升级过程中，停止运行ipfs进程

### 手动升级

为了能够手动升级`ipfs`，你将需要手动的执行所有的仓库迁移。步骤如下：

* 确认`ipfs`进程是否被关闭
* (可选)备份你的ipfs数据文件夹（例如：`cp -aL ~/.ipfs ~/.ipfs.bk`）
* 下载并安装最新版本的`ipfs`，[https://dist.ipfs.io/#go-ipfs](https://dist.ipfs.io/#go-ipfs)
* 执行`ipfs`进程

当一个知识仓库需要被迁移，`ipfs`会通知到用户下载并安装`fs-repo-migrations`来执行升级。如果你希望自动完成这些步骤，请在开启进程时，附`--migrate`的参数。

仓库迁移也可以手动执行，通过下载最新版本的`fs-repo-migrations`,[下载地址](下载地址)与[操作指南](操作指南)。

## 快速定位问题

### 帮助！
如果你遇到任何问题，可以在这里得到帮助[#ipfs](https://ipfs.io/docs/#community)或者[the mailing list](https://ipfs.io/docs/#community)

### 检测Go的版本

IPFS需要Go 1.7.0或更高版本。检测你所安装的Go版本，使用`go version`。下面是我的执行结果。

```
$ go version
go version go1.7 linux/amd64
```

如果你需要更新，建议从[https://golang.org/doc/install](https://golang.org/doc/install)下载。安装包管理器通常会包含历史的Go安装包。

### 安装 FUSE
想要了解更多关于如何设置FUSE（让你能够挂载文件系统），参考[github.com/ipfs/go-ipfs/blob/master/docs/fuse.md](github.com/ipfs/go-ipfs/blob/master/docs/fuse.md)

**Comment by chenkehao** [comment]
好的

**Comment by chenkehao** [comment]
翻译完成 进入校对流程
1.回复“校对认领” 需整理成一个整体的markdown文件
2.收到站长回复OK后 开始校对
3.校对完成后提交站长验收(这个问题下面回复即可)

**Comment by candy-yangliu** [comment]
校对认领

**Comment by candy-yangliu** [comment]
# 安装 IPFS

有多种方法可以将 IPFS 安装到您的电脑上。我们在建议您使用安装包进行安装的同时，也提供了其他安装方法：

-  使用安装包安装（推荐） 
-  通过 ipfs-update 安装 
-  编译源码安装
-  升级 IPFS 安装 
-  通过故障排查安装

请注意，所有安装说明都会用到 **命令行** 工具。我们使用 `$` 来表示命令提示符，即输入命令时每一行都需要以此符号开头，但输出结果行并不会以此符号开头。

## 使用安装包安装

首先，下载适合您操作系统的 IPFS 版本：

[下载IPFS到您的电脑](https://dist.ipfs.io/#go-ipfs)

### Mac OS X 和 Linux 系统

下载后解压安装包，将 `ipfs` 库文件拷贝到可执行路径，使用 `install.sh` 脚本文件进行安装：

    $ tar xvfz go-ipfs.tar.gz
    $ cd go-ipfs
    $ ./install.sh

测试结果:

    $ ipfs help
    USAGE:

            ipfs - Global p2p merkle-dag filesystem.
    ...

恭喜！现在您已经成功将IPFS安装到电脑上。

[开始使用IPFS ->](https://docs.ipfs.io/introduction/usage/)

## Windows 系统

下载后解压安装包，将 `ipfs.exe` 拷贝到可执行路径 `%PATH%` 。

测试结果:

    $ ipfs help
    USAGE:
        
         ipfs - Global p2p merkle-dag filesystem.
        ...

恭喜！现在您已经成功将IPFS安装到电脑上。

[开始使用IPFS ->](https://docs.ipfs.io/introduction/usage/)

## 通过 ipfs-update 安装 

`ipfs-update` 是一个命令行工具，用来安装与升级 `ipfs` 库文件。

### 下载 ipfs-update

可以从 [https://dist.ipfs.io/#ipfs-update](https://dist.ipfs.io/#ipfs-update) 下载到适合您操作系统的`ipfs-update` 版本。

如果拥有 Go 环境（>=1.8），您也可以这样安装：

    $ go get -u github.com/ipfs/ipfs-update

安装新版本或者更新 `ipfs`  时 ，请确认您使用的是最新版的 `ipfs-update` 。

### 通过 ipfs-update 来安装 ipfs

`ipfs-update versions` 包含所有可供下载和使用的 `ipfs` 版本。

    $ ipfs-update versions
    v0.3.2
    v0.3.4
    v0.3.5
    v0.3.6
    v0.3.7
    v0.3.8
    v0.3.9
    v0.3.10
    v0.3.11
    v0.4.0
    v0.4.1
    v0.4.2
    v0.4.3
    v0.4.4
    v0.4.5
    v0.4.6
    v0.4.7-rc1

使用 `ipfs-update install latest` 命令将会安装最新的可用版本：

    $ ipfs-update install latest
    fetching go-ipfs version v0.4.7-rc1
    binary downloaded, verifying...
    success!
    stashing old binary
    installing new binary to /home/hector/go/bin/ipfs
    checking if repo migration is needed...
    Installation complete!

请注意，最新版本（即以vX.X.X-rcX格式发布的版本）可能会存在稳定性问题。因此，建议您安装指定版本，例如，`ipfs-update install v0.4.6` 。

## 编译源码安装

> 警告：今后将不再支持使用命令行 `go get` 来安装 IPFS。

您也可以通过编译源码的方式安装IPFS。Mac OS X 或 Linux 用户可以参考 [readme](https://github.com/ipfs/go-ipfs#build-from-source) 进行安装。Windows用户请参考这份[安装说明](https://github.com/ipfs/go-ipfs/blob/master/docs/windows.md)。

## 更新 IPFS 

`ipfs` 更新（或安装历史版本）会涉及到仓库的升级，该过程要通过使用 [fs-repo-migrations](https://dist.ipfs.io/#fs-repo-migrations) 工具来完成。

### 使用 ipfs-update 进行更新

如前文所述，安装较新或者历史版本 `ipfs` 的过程中，如果有需要，您可以使用 `ipfs-update install` 命令行下载并运行 `fs-repo-migrations`。这是最新简单的升级方式。

> 警告：请确保更新过程中并没有运行 ipfs 进程。

### 手动更新

为了能够手动更新 `ipfs` ，您需要手动执行所有的仓库迁移。步骤如下：

* 终止 `ipfs` 进程
* 备份 `ipfs` 数据文件夹，比如使用 `cp -aL ~/.ipfs ~/.ipfs.bk` 命令行 (可选)
* 可以从 [https://dist.ipfs.io/#go-ipfs](https://dist.ipfs.io/#go-ipfs) 下载并安装最新版本的 `ipfs`
* 运行 `ipfs` 进程

需要迁移某个仓库时，`ipfs` 会通知用户下载并安装 `fs-repo-migrations` 来进行更新。如果您希望自动执行这些步骤，请使用 `-- migrate` 命令启动进程。

仓库迁移也可以手动进行。请从 [https://dist.ipfs.io/#fs-repo-migrations](https://dist.ipfs.io/#fs-repo-migrations) 下载最新版本的 `fs-repo-migrations`和 [操作指南](https://github.com/ipfs/fs-repo-migrations/blob/master/run.md) 。

## 通过故障排查安装

### 寻求帮助

如果您遇到任何问题，可以访问 [#ipfs](https://docs.ipfs.io/introduction/#community) 获得在线支持，或发送邮件到 [客服邮件](https://docs.ipfs.io/introduction/#community) 寻求帮助。

### 检测 Go 版本

IPFS 需要 Go 1.7.0 或更高版本。输入 `go version` 可以检测您所安装的 Go 版本。下面是我的运行结果：

    $ go version
    go version go1.7 linux/amd64

如果需要更新，建议从 [canonical Go packages](https://golang.org/doc/install) 下载。安装包管理器通常会包含旧历史版本的 Go 安装包。

### 安装 FUSE

关于如何设置 FUSE 来挂载文件系统，详情请见 [github.com/ipfs/go-ipfs/blob/master/docs/fuse.md](github.com/ipfs/go-ipfs/blob/master/docs/fuse.md)。

**Comment by chenkehao** [comment]
重复篇目
